AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  energy_weather_lmp_tbl_crud

  Sample SAM Template for energy_weather_lmp_tbl_crud

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  EnergyWeatherLmpCrudFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: energy_weather_lmp/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  EnergyWeatherLmpCrudApi:
    Description: "API Gateway endpoint URL for Prod stage for EnergyWeatherLmpCrud function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  EnergyWeatherLmpCrudFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt EnergyWeatherLmpCrudFunction.Arn
  EnergyWeatherLmpCrudFunctionIamRole:
    Description: "Implicit IAM Role created forEnergyWeatherLmpCrud function"
    Value: !GetAtt EnergyWeatherLmpCrudFunctionRole.Arn
